package com.codi.superman.base.common;

/**
 * 错误常量
 *
 * @author shi.pengyan
 * @date 2016年11月8日 下午1:58:29
 */
public interface ErrorConst {

    /****/
    String USER_CODE_IS_SHORT = "USER_CODE_IS_SHORT";
    String USER_CODE_HAS_EXIST = "USER_CODE_HAS_EXIST";
    String USER_NOT_EXIST = "USER_NOT_EXIST";
    String USER_NAME_OR_PWD_ERROR = "USER_NAME_OR_PWD_ERROR";
    String USER_NOT_LOGIN = "USER_NOT_LOGIN";
    String USER_SESSION_TIMEOUT = "USER_SESSION_TIMEOUT";
    String USER_HAS_LOCKED = "USER_HAS_LOCKED";
    String USER_ORIGIN_PWD_ERROR = "USER_ORIGIN_PWD_ERROR";
    String USER_PWD_LENGTH_ERROR = "USER_PWD_LENGTH_ERROR";
    String USER_CHANGE_PWD_ORIGIN_AND_NEW_ARE_SAME_ERROR = "USER_CHANGE_PWD_ORIGIN_AND_NEW_ARE_SAME_ERROR";
    String USER_BEGIN_END_DATE_ERROR = "USER_BEGIN_END_DATE_ERROR";

    String USER_LOCK_SELF_ERROR = "USER_LOCK_SELF_ERROR";
    String USER_DELETE_SELF_ERROR = "USER_DELETE_SELF_ERROR";

    //USERROLE
    String USERROLE_HAS_EXIST = "USERROLE_HAS_EXIST";

    String ROLE_CODE_HAS_EXIST = "ROLE_CODE_HAS_EXIST";
    String ROLE_HAS_USER_ROLE_REF = "ROLE_HAS_USER_ROLE_REF";

    //ROLEPRIV
    String ROLEPRIV_HAS_EXIST = "ROLEPRIV_HAS_EXIST";

    //PRIV Module
    String PRIV_IS_NULL = "PRIV_IS_NULL";
    String PRIV_CODE_HAS_EXIST = "PRIV_CODE_HAS_EXIST";
    String PRIV_HAS_ROLE_PRIV_REF = "PRIV_HAS_ROLE_PRIV_REF";

    //APP
    String APP_HAS_REF = "APP_HAS_REF";
    String APP_VERSION_ERROR = "APP_VERSION_ERROR";

    String NO_PERMISSION = "NO_PERMISSION";

    //Banner
    String BANNER_ORDER_ERROR = "BANNER_ORDER_ERROR";
    String BANNER_ORDER_EXIST = "BANNER_ORDER_EXIST";

    String SYS_UPLOAD_DEL_ERROR = "SYS_UPLOAD_DEL_ERROR";

    //Group
    String GROUP_BIZ_CODE_ERROR = "GROUP_BIZ_CODE_ERROR";

}
