-- 1.0.9
-- production env
INSERT INTO SYS_PARAM (PARAM_CODE, PARAM_VALUE, STATE, DESCRIPTION, CREATE_DATE)
    VALUE ('QINIU_ACCESS_KEY', 'fmHkjN_J43so0xCf8gvZr62yl4gIup65woc9zoKg', 'A', 'qiniu access key', CURRENT_TIMESTAMP);

INSERT INTO SYS_PARAM (PARAM_CODE, PARAM_VALUE, STATE, DESCRIPTION, CREATE_DATE)
    VALUE ('QINIU_SECRET_KEY', 'fGnFS0w4IkPsoC1Oc549vfkfOOTMaM6YqgT4kEaD', 'A', 'qiniu secret key', CURRENT_TIMESTAMP);


INSERT INTO SYS_FILE_BUCKET (BUCKET_ID, BUCKET_NAME, BUCKET_CODE, HOST_NAME, IS_PUBLIC)
VALUES (1, '公有空间', 'file-public', '//file.cd121.com/', 1);
INSERT INTO SYS_FILE_BUCKET (BUCKET_ID, BUCKET_NAME, BUCKET_CODE, HOST_NAME, IS_PUBLIC)
VALUES (2, '私有空间', 'file-priv', '//file-priv.cd121.com/', 0);
