-- 1.0.1
-- shi.pengyan
-- 只有在开发环境下执行
-- Test Directory and priv
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (2, 0, 'DIRECTORY_TEST', 'Test', 0, NULL, NULL, 'Test Directory');

INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (201, 2, 'MENU_TEST_PAGE', 'Test Page', 1, 'test/index', '/test/index', 'Test Page Management');

INSERT INTO `SYS_ROLE_PRIV` (ROLE_ID, PRIV_ID) VALUES (1, 2), (1, 201);

--
-- 1.0.9
-- dev env
INSERT INTO SYS_PARAM (PARAM_CODE, PARAM_VALUE, STATE, DESCRIPTION, CREATE_DATE)
    VALUE ('QINIU_ACCESS_KEY', 'fmHkjN_J43so0xCf8gvZr62yl4gIup65woc9zoKg', 'A', 'qiniu access key', CURRENT_TIMESTAMP);

INSERT INTO SYS_PARAM (PARAM_CODE, PARAM_VALUE, STATE, DESCRIPTION, CREATE_DATE)
    VALUE ('QINIU_SECRET_KEY', 'fGnFS0w4IkPsoC1Oc549vfkfOOTMaM6YqgT4kEaD', 'A', 'qiniu secret key', CURRENT_TIMESTAMP);


INSERT INTO SYS_FILE_BUCKET (BUCKET_ID, BUCKET_NAME, BUCKET_CODE, HOST_NAME, IS_PUBLIC)
VALUES (1, '公有空间', 'dev-file-public', '//dev-file.cd121.com/', 1);
INSERT INTO SYS_FILE_BUCKET (BUCKET_ID, BUCKET_NAME, BUCKET_CODE, HOST_NAME, IS_PUBLIC)
VALUES (2, '私有空间', 'dev-file-priv', '//dev-file-priv.cd121.com/', 0);
