-- 流程管理
-- 44x,45x

-- 目录
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (3, 0, 'DIRECTORY_BPMN', '流程管理', 0, NULL, NULL, '流程管理');

-- 菜单
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (440, 3, 'MENU_BPMN_RULE', '流程规则', 1, 'bpmn/rule', '/bpmn/rule', '流程规则');

-- bpmn priv
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, DESCRIPTION)
VALUES (441, 3, 'sys:bpmn:save', 'sys:bpmn:save', 2, '保存');
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, DESCRIPTION)
VALUES (442, 3, 'sys:bpmn:delete', 'sys:bpmn:delete', 2, '删除');
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, DESCRIPTION)
VALUES (443, 3, 'sys:bpmn:query', 'sys:bpmn:query', 2, '查询');

INSERT INTO `SYS_ROLE_PRIV` (ROLE_ID, PRIV_ID) VALUES (1, 3), (1, 440), (1, 441), (1, 442), (1, 443);

-- TODO 暂时不考虑数据权限问题
-- 菜单
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (450, 3, 'MENU_BPMN_INSTANCE', '流程实例', 1, 'bpmn/instance', '/bpmn/instance', '流程实例');
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (451, 3, 'MENU_BPMN_MY_TASK', '待办任务', 1, 'bpmn/myTask', '/bpmn/myTask', '代办任务');
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (452, 3, 'MENU_BPMN_MY_TASK_HIS', '任务历史', 1, 'bpmn/myTaskHis', '/bpmn/myTaskHis', '任务历史');
INSERT INTO `SYS_PRIV` (PRIV_ID, PARENT_PRIV_ID, PRIV_CODE, PRIV_NAME, TYPE, URL, PATH, DESCRIPTION)
VALUES (453, 3, 'MENU_BPMN_APPLY', '流程申请', 1, 'bpmn/apply', '/bpmn/apply', '流程申请');
--
INSERT INTO `SYS_ROLE_PRIV` (ROLE_ID, PRIV_ID) VALUES (1, 450), (1, 451), (1, 452), (1, 453);

