INSERT INTO `SYS_COMMON_GROUP`
(GROUP_ID,GROUP_NAME,BIZ_CODE,DESCRIPTION,BIZ_GROUP_CODE)
VALUES(1001,'主站信息披露','bulletin_www_info','主站信息披露','bulletin');
INSERT INTO `SYS_COMMON_GROUP`
(GROUP_ID,GROUP_NAME,BIZ_CODE,DESCRIPTION,BIZ_GROUP_CODE)
VALUES(1002,'手机公告','bulletin_APP','手机公告','bulletin');
INSERT INTO `SYS_COMMON_GROUP`
(GROUP_ID,GROUP_NAME,BIZ_CODE,DESCRIPTION,BIZ_GROUP_CODE)
VALUES(1003,'基金学堂','bulletin_fundSchool','基金学堂','bulletin');
INSERT INTO `SYS_COMMON_GROUP`
(GROUP_ID,GROUP_NAME,BIZ_CODE,DESCRIPTION,BIZ_GROUP_CODE)
VALUES(1004,'要闻直播','bulletin_newsBroadcast','要闻直播','bulletin');
